version: '3'
services:
  app:
    stdin_open: true # interactive mode
    tty: true # if you want to show logs in docker 
    container_name: vp_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    restart: on-failure
    volumes:
      - ./vp_container:/vp_container
